apiVersion: skaffold/v2beta9
kind: Config
build:
  artifacts:
    - image: devpies/client-app-identity
      context: identity/application
      sync:
        manual:
          - src: "*.ts"
            dest: .
      docker:
        dockerfile: Dockerfile
        target: dev
    - image: devpies/client-com-identity
      context: identity/component
      sync:
        manual:
          - src: "*.go"
            dest: .
      docker:
        dockerfile: Dockerfile
        target: dev
  local:
    push: false
    useDockerCLI: true
    useBuildkit: true
deploy:
  kubectl:
    manifests:
      - ./__infra__/*
