apiVersion: apps/v1
kind: Deployment
metadata:
  name: mic-identity-depl
spec:
  selector:
    matchLabels:
      app: mic-identity
  template:
    metadata:
      labels:
        app: mic-identity
    spec:
      containers:
        - image: devpies/mic-identity:latest
          name: mic-identity
          resources:
            requests:
              cpu: "100m"
              memory: "100Mi"
            limits:
              cpu: "250m"
              memory: "250Mi"
          env:
            - name: NATS_URL
              value: "nats://nats-svc:4222"
            - name: CLIENT_ID
              value: "mic-identity"
            - name: CLUSTER_ID
              value: "devpie-client"
            - name: POSTGRES_DB
              value: postgres
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_HOST
              value: mic-db-identity-svc
      initContainers:
        - name: schema-migration
          image: devpies/mic-db-identity-migration:v000003
          env:
            - name: DB_URL
              value: postgresql://postgres:postgres@mic-db-identity-svc:5432/postgres?sslmode=disable
          command: ["migrate"]
          args:
            ["-path", "/migrations", "-verbose", "-database", "$(DB_URL)", "up"]
