apiVersion: v1
kind: ConfigMap
metadata:
  name: self-signed
data:
  cert.pem: |
    -----BEGIN CERTIFICATE-----
    MIIEITCCAomgAwIBAgIQdtrV+cJ4NfIr7n7MCJE9FDANBgkqhkiG9w0BAQsFADBh
    MR4wHAYDVQQKExVta2NlcnQgZGV2ZWxvcG1lbnQgQ0ExGzAZBgNVBAsMEmljdW1t
    aW5nQFhJTjcxNjU1MjEiMCAGA1UEAwwZbWtjZXJ0IGljdW1taW5nQFhJTjcxNjU1
    MjAeFw0yMTAyMDEyMzA2MTdaFw0yMzA1MDEyMjA2MTdaMEYxJzAlBgNVBAoTHm1r
    Y2VydCBkZXZlbG9wbWVudCBjZXJ0aWZpY2F0ZTEbMBkGA1UECwwSaWN1bW1pbmdA
    WElONzE2NTUyMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAyfvpTmdh
    1GL7chV0UhrQoBJ5GU8rg00DyzUglyHdH29ZepWcujF2U7dM9x7M8gKHkEbNPshn
    gjrMdUGPD46UWpSTKvmfvn8xeGSfMNl/1qqBjbVt68I59Z31RswnoGim2pLXRud+
    SlJosVm9x+3zacBWcwBF0bQEiuxLS+mYMJsvT1472f7Qg7XEnPCFE0Uxp2M646hu
    Bv7brcXDq1n629CzzKb1/20aS/0uCmIB6bxjTQK/OvC7ETITFoWVRsdj1ZQVyfFr
    gTwlJR5xqievoRj9UlFMMzGhuSjt9qQtChm8LVrcQRaPcXUBBob7I6R20Dfqg8PV
    JQZBxpc03PY99wIDAQABo3AwbjAOBgNVHQ8BAf8EBAMCBaAwEwYDVR0lBAwwCgYI
    KwYBBQUHAwEwHwYDVR0jBBgwFoAUB/QgHTwX2G1Z6DJVWkD89adKP/swJgYDVR0R
    BB8wHYIbY2xpZW50LWJhY2tlbmQuZGV2cGllLmxvY2FsMA0GCSqGSIb3DQEBCwUA
    A4IBgQAjOsBne7ht78SrBlYHtLuW5XAW5GDL6lwfJDYzmET/fU5nsIAPKlhUdfeq
    kJ0ItaAzjjhYTmYqLq/+5l4OL7u+6sVD427ES4+jKit3/MPVyrfhfEKOBr+hFw8h
    0sxGtwTH3i4b5J2kryrYA70EuVXfV/+JiNMc53MeazjMRcvX0f3GTg3dfemSR6GT
    pWgeVb7ruac16ikFBxELnivxfUSRePi8HsNGLO5Z+Otw6fPwWWfqyuao295iPSFs
    w3cRmHEnA38F9egC7Z4xcEGy5jzLN2rv5cbhCA3Mmq6gdLxSWPqaSfhl/eFxSg1R
    EzH0vv4uYjS2FHhrsIPMDW4PaRDXIeiO+iQYcoZU3elKYh0Jij9POsWsoN3ThBxR
    newiSQwiVKDD5wtW2KPrr/ErHMCNcngEmPZfpgWyDmkGCHknNIxqaS+Sa/GaPd2h
    FO+y5EkfInPfkazJtzm3BTgEpL1uIy+pyxvPByQRK3rI3MMFpe1qFCdSOPld4Moh
    H+mjp80=
    -----END CERTIFICATE-----
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: traefik-ingress-controller
---
kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: traefik-ingress-controller
  labels:
    k8s-app: traefik-ingress-lb
spec:
  selector:
    matchLabels:
      k8s-app: traefik-ingress-lb
      name: traefik-ingress-lb
  template:
    metadata:
      labels:
        k8s-app: traefik-ingress-lb
        name: traefik-ingress-lb
    spec:
      tolerations:
        - effect: NoSchedule
          operator: Exists
      serviceAccountName: traefik-ingress-controller
      terminationGracePeriodSeconds: 60
      containers:
        - image: traefik:2.3
          name: traefik-ingress-lb
          ports:
            - name: http
              containerPort: 80
            - name: websecure
              containerPort: 443
            - name: admin
              containerPort: 8080
          securityContext:
            capabilities:
              drop:
                - ALL
              add:
                - NET_BIND_SERVICE
          args:
            - --providers.kubernetesingress=true
            - --providers.kubernetesingress.ingressendpoint.hostname=localhost
            - --providers.kubernetesingress.certauthfilepath=/certs/self-signed.pem
            - --api.dashboard=true
            - --api.insecure=true
            - --entrypoints.web.address=:80
            # permanent redirecting of all requests on http (80) to https (443)
            - --entrypoints.web.http.redirections.entryPoint.to=websecure
            - --entrypoints.web.http.redirections.entryPoint.scheme=https
            - --entrypoints.websecure.address=:443
            - --serversTransport.insecureSkipVerify=true
            - --log=true
            - --log.level=INFO
            - --accesslog=true
          volumeMounts:
            - name: certs
              mountPath: /certs/self-signed.pem
              readOnly: true
      volumes:
        - name: certs
          configMap:
            name: self-signed
---
kind: Service
apiVersion: v1
metadata:
  name: traefik-ingress-service
spec:
  selector:
    k8s-app: traefik-ingress-lb
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      name: web
    - protocol: TCP
      port: 443
      name: websecure
    - protocol: TCP
      port: 8080
      name: admin
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: traefik-ingress-controller
rules:
  - apiGroups:
      - ""
    resources:
      - services
      - endpoints
      - secrets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - extensions
      - networking.k8s.io
    resources:
      - ingresses
      - ingressclasses
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - extensions
    resources:
      - ingresses/status
    verbs:
      - update
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: traefik-ingress-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: traefik-ingress-controller
subjects:
  - kind: ServiceAccount
    name: traefik-ingress-controller
    namespace: default