name: publish-mic-projects

on:
  push:
    paths:
      - ".github/workflows/publish-mic-projects.yml"
      - "projects/**"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Image
        env:
          NEW_IMAGE: ${{ github.repository_owner }}/mic-projects:$(git rev-parse --short head)
        run: |
          docker build ./projects --tag ghcr.io/$NEW_IMAGE
          docker push ghcr.io/$NEW_IMAGE

      - uses: actions/checkout@v2
        with:
          repository: "https://github.com/devpies/devpie-infra"

      - name: Setup Kustomize
        uses: imranismail/setup-kustomize@v1
        with:
          kustomize-version: "3.6.1"

      - name: Update Kubernetes resources
        run: |
          cd kustomize/base
          kustomize edit set image mic-projects=$NEW_IMAGE
          cat kustomization.yaml

      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -am "Updated projects image: $NEW_IMAGE"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
