name: publish-mic-projects

on:
  push:
    paths:
      - ".github/workflows/publish-mic-projects.yml"
      - "projects/**"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Image
        env:
          IMAGE: ${{ github.repository_owner }}/mic-projects
        run: |
          export VERSION=$(git rev-parse --short HEAD)
          docker build ./projects --tag ghcr.io/$IMAGE:$VERSION
          docker push ghcr.io/$IMAGE:$VERSION
          echo $IMAGE:$VERSION > image.txt
      - uses: actions/checkout@v2
        with:
          repository: ${{ github.repository_owner }}/devpie-infra
          token: ${{ secrets.PAT }}
          path: devpie-infra
      - run: |
          export NEW_IMAGE=$(cat image.txt)
          cd devpie-infra
          ls
          sed -i "" "s/mic-projects:.*/$NEW_IMAGE/" ./manifests/mic-projects-depl.yaml
          git config --local user.email github-actions@github.com
          git config --local user.name github-actions
          git add .
          git commit -m "release $IMAGE:$VERSION"
          git push
