name: publish-mic-projects

on:
  push:
    paths:
    - ".github/workflows/publish-mic-projects.yml"
    - "projects/**"

jobs:
    publish:
      runs-on: ubuntu-latest
      steps:
          - uses: actions/checkout@v2
          - uses: docker/login-action@v1
            with:
              registry: ghcr.io
              username: ${{ github.repository_owner }}
              password: ${{ secrets.GITHUB_TOKEN }}

          - name: projects microservice
            run: |
              docker build ./projects --tag ghcr.io/${{ github.repository_owner }}/mic-projects:latest
              docker push ghcr.io/${{ github.repository_owner }}/mic-projects:latest
